### ISSUE TITLE
Entity unavailible 

### ISSUE THREAD

**Issue by TechyGuy17** [Ekman/home-assistant-hiveos#9]
After a few weeks of no problems the entity for my hiveOS rig shows as unavailible
![image](https://github.com/Ekman/home-assistant-hiveos/assets/65623992/722004a1-edfe-4f3d-9965-79554ca01928)
Tried disabling then enabling the integration but cant get the miner to show as availible. And yes the rig is online and showing in the hiveos dashboard.

Following error can be found in the system logs:
```
custom_components.hiveos.exceptions.HiveOsApiException: Failed response: 403 {'message': 'Cannot use API keys to access free farms', 'code': 403}
```

So it seems to be an issue after the recent payed plan changes

**Comment by Ekman** [comment]
Looks like HiveOS only allows subscribed farms to access the API. Not much I can do about that unfortunately. You'll have to pay for HiveOS to use this integration.
